name: flutter_sqlite3_extension
description: Create a Flutter package for loading a sqlite3 extension
version: 1.0.0
repository: https://github.com/rodydavis/flutter_sqlite3_extension_cli
homepage: https://github.com/rodydavis/flutter_sqlite3_extension_cli

executables:
  flutter_sqlite3_extension:

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
